[tool.poetry]
name = "qdrant-mcp-server"
version = "1.0.0"
description = "MCP Server for Qdrant Knowledge Graph"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "qdrant_mcp_server"}]

[tool.poetry.dependencies]
python = "^3.8"
fastmcp = "^0.1.0"
qdrant-client = "^1.1.1"
openai = "^0.27.0"
pydantic = "^1.10.0"
python-dotenv = "^0.19.0"
numpy = "^1.23.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"
mypy = "^0.982"
pytest = "^7.2.0"
pytest-asyncio = "^0.20.0"
types-python-dotenv = "^0.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.21.0"
httpx = "^0.24.1"
requests-mock = "^1.11.0"
fastmcp-testing = "^0.1.2"